/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.trabalhoFinal.UI;

import com.trabalhoFinal.Dominio.ExameSangue;
import com.trabalhoFinal.Lista.GerenciadorDeExame;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author lucas
 */
public class CadastrarExameSanguePainel extends javax.swing.JPanel {

    private GerenciadorDeExame gde;
    private App app;

    /**
     * Creates new form CadastrarExamePanel
     */
    public CadastrarExameSanguePainel(GerenciadorDeExame gde, App app) {
        initComponents();
        this.gde = gde;
        this.app = app;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        nome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        cadastroExameSangueTitulo = new javax.swing.JLabel();
        cadastrarBtn = new javax.swing.JButton();
        txtHemoglobina = new javax.swing.JTextField();
        txtLeucocito = new javax.swing.JTextField();
        txtPlaqueta = new javax.swing.JTextField();
        hemoglobina = new javax.swing.JLabel();
        leucocito = new javax.swing.JLabel();
        plaqueta = new javax.swing.JLabel();
        voltarBtn = new javax.swing.JButton();

        Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Id.setText("Id");

        nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nome.setText("Nome");

        cpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cpf.setText("CPF");

        cadastroExameSangueTitulo.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        cadastroExameSangueTitulo.setText("Cadastro de Exames de Sangue");

        cadastrarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        hemoglobina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hemoglobina.setText("Hemoglobina");

        leucocito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        leucocito.setText("Leucocitos");

        plaqueta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plaqueta.setText("Plaquetas");

        voltarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        voltarBtn.setText("Voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(cadastroExameSangueTitulo)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(voltarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plaqueta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Id, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hemoglobina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leucocito, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(txtHemoglobina, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(txtLeucocito, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(txtPlaqueta, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addComponent(cadastrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(cadastroExameSangueTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Id)
                        .addGap(12, 12, 12)
                        .addComponent(nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hemoglobina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leucocito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plaqueta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHemoglobina, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLeucocito, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastrarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(206, 206, 206))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        JTextField[] campos = {txtId, txtNome, txtCpf, txtHemoglobina, txtLeucocito, txtPlaqueta};

        for (JTextField campo : campos) {
            if (campo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
                return;
            }
        }

        if (gde.procurarExame(txtId.getText()) != null) {
            JOptionPane.showMessageDialog(this, "ID já cadastrado, mude os caracteres do ID do exame.");
            return;
        }

        String id = txtId.getText();
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        double hemoglobina;
        double leucocitos;
        double plaquetas;

        try {
            hemoglobina = Double.parseDouble(txtHemoglobina.getText());
            leucocitos = Double.parseDouble(txtLeucocito.getText());
            plaquetas = Double.parseDouble(txtPlaqueta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira números válidos nos campos hemoglobina, leucócitos e plaquetas.");
            return;
        }

        Date dataAtual = new Date();

        ExameSangue novoExame = new ExameSangue(id, dataAtual, nome, cpf, hemoglobina, leucocitos, plaquetas);
        JOptionPane.showMessageDialog(this, "Exame cadastrado com sucesso!");
        gde.cadastrarExame(novoExame);
        limparCampos();
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void limparCampos() {
        // Limpa os campos de texto após o cadastro
        txtId.setText("");
        txtNome.setText("");
        txtCpf.setText("");
        txtHemoglobina.setText("");
        txtLeucocito.setText("");
        txtPlaqueta.setText("");
    }

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        app.mudaPainel(App.PAINEL_PRINCIPAL);
        limparCampos();
    }//GEN-LAST:event_voltarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JLabel cadastroExameSangueTitulo;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel hemoglobina;
    private javax.swing.JLabel leucocito;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel plaqueta;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtHemoglobina;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLeucocito;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPlaqueta;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables

}
