/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.trabalhoFinal.UI;

import com.trabalhoFinal.Calculo.CalculaEstatistica;
import com.trabalhoFinal.Dominio.Exame;
import com.trabalhoFinal.Lista.GerenciadorDeExame;
import java.util.List;

/**
 *
 * @author lucas
 */
public class ExibirEstatisticasPainel extends javax.swing.JPanel {

    
    private GerenciadorDeExame gerenciadorDeExame;
    private App app;

    /**
     * Creates new form ExibirEstatisticas
     */
    public ExibirEstatisticasPainel(GerenciadorDeExame gerenciadorDeExame, App app) {
        super();
        initComponents();
        
        this.gerenciadorDeExame = gerenciadorDeExame;
        this.app = app;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelTotalExames = new javax.swing.JLabel();
        labelTotalExameSangue = new javax.swing.JLabel();
        labelTotalExameBioquimico = new javax.swing.JLabel();
        labelSomaTotalLeucocitos = new javax.swing.JLabel();
        labelMediaTotalGlicose = new javax.swing.JLabel();
        txtTotalExames = new javax.swing.JTextField();
        txtTotalExamesSangue = new javax.swing.JTextField();
        txtTotalExamesBioquimicos = new javax.swing.JTextField();
        txtTotalSomaLeucocitos = new javax.swing.JTextField();
        txtMediaTotalGlicose = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 600));

        voltarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        voltarBtn.setText("Voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Estatísticas");

        labelTotalExames.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalExames.setText("Total Exames");

        labelTotalExameSangue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalExameSangue.setText("Total Exames de Sangue");

        labelTotalExameBioquimico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalExameBioquimico.setText("Total Exames Bioquímicos");

        labelSomaTotalLeucocitos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSomaTotalLeucocitos.setText("Soma Total de Leucócitos dos Exames Bioquímicos");

        labelMediaTotalGlicose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMediaTotalGlicose.setText("Média Total de Glicose por Exame Bioquímico");

        txtTotalExames.setEditable(false);

        txtTotalExamesSangue.setEditable(false);

        txtTotalExamesBioquimicos.setEditable(false);

        txtTotalSomaLeucocitos.setEditable(false);

        txtMediaTotalGlicose.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(314, 314, 314))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelTotalExameSangue)
                        .addComponent(labelTotalExames)
                        .addComponent(labelTotalExameBioquimico)
                        .addComponent(labelSomaTotalLeucocitos)
                        .addComponent(labelMediaTotalGlicose))
                    .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalExames, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalExamesSangue, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalExamesBioquimicos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSomaLeucocitos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMediaTotalGlicose, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalExames)
                    .addComponent(txtTotalExames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalExameSangue)
                    .addComponent(txtTotalExamesSangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalExameBioquimico)
                    .addComponent(txtTotalExamesBioquimicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSomaTotalLeucocitos)
                    .addComponent(txtTotalSomaLeucocitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMediaTotalGlicose)
                    .addComponent(txtMediaTotalGlicose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        app.mudaPainel(App.PAINEL_PRINCIPAL);
    }//GEN-LAST:event_voltarBtnActionPerformed

    void atualizarEstatisticas() {
        List<Exame> exames = gerenciadorDeExame.visualizarExames();
        txtTotalExames.setText(String.valueOf(CalculaEstatistica.calcularTotalExames(exames)));
        txtTotalExamesSangue.setText(String.valueOf(CalculaEstatistica.calcularTotalExamesSangue(exames)));
        txtTotalExamesBioquimicos.setText(String.valueOf(CalculaEstatistica.calcularTotalExamesBioquimicos(exames)));
        txtTotalSomaLeucocitos.setText(String.format("%.2f", CalculaEstatistica.calcularSomaLeucocitos(exames)));
        txtMediaTotalGlicose.setText(String.format("%.2f", CalculaEstatistica.calcularMediaGlicose(exames)));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelMediaTotalGlicose;
    private javax.swing.JLabel labelSomaTotalLeucocitos;
    private javax.swing.JLabel labelTotalExameBioquimico;
    private javax.swing.JLabel labelTotalExameSangue;
    private javax.swing.JLabel labelTotalExames;
    private javax.swing.JTextField txtMediaTotalGlicose;
    private javax.swing.JTextField txtTotalExames;
    private javax.swing.JTextField txtTotalExamesBioquimicos;
    private javax.swing.JTextField txtTotalExamesSangue;
    private javax.swing.JTextField txtTotalSomaLeucocitos;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
