/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.trabalhoFinal.UI;

import com.trabalhoFinal.Lista.GerenciadorDeExame;
import static com.trabalhoFinal.UI.App.PAINEL_CADASTRAR_EXAME_BIOQUIMICO;
import static com.trabalhoFinal.UI.App.PAINEL_CADASTRAR_EXAME_SANGUE;
import static com.trabalhoFinal.UI.App.PAINEL_EDITAR_EXAME_BIOQUIMICO;
import static com.trabalhoFinal.UI.App.PAINEL_EDITAR_EXAME_SANGUE;
import static com.trabalhoFinal.UI.App.PAINEL_EXIBIR_ESTATISTICAS;
import static com.trabalhoFinal.UI.App.PAINEL_PROCURAR_EXAME;
import static com.trabalhoFinal.UI.App.PAINEL_VISUALIZAR_EXAMES;

/**
 *
 * @author lucas
 */
public class PainelPrincipal extends javax.swing.JPanel {

    private GerenciadorDeExame gerenciadorDeExame;
    private App app;

    public PainelPrincipal(GerenciadorDeExame gerenciadorDeExame, App app) {
        super();
        initComponents();
        this.gerenciadorDeExame = gerenciadorDeExame;
        this.app = app;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarExameSangueBtn = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        procurarBtn = new javax.swing.JButton();
        visualizarExameBtn = new javax.swing.JButton();
        cadastrarExameBioBtn = new javax.swing.JButton();
        editarExameSangueBtn = new javax.swing.JButton();
        editarExameBioBtn = new javax.swing.JButton();
        exibirEstatisticaBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        cadastrarExameSangueBtn.setText("Cadastrar Exame de Sangue");
        cadastrarExameSangueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarExameSangueBtnActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Titulo.setText("Laboratório");

        procurarBtn.setText("Procurar Exame");
        procurarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarBtnActionPerformed(evt);
            }
        });

        visualizarExameBtn.setText("Visualizar Exames");
        visualizarExameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarExameBtnActionPerformed(evt);
            }
        });

        cadastrarExameBioBtn.setText("Cadastrar Exame Bioquimico");
        cadastrarExameBioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarExameBioBtnActionPerformed(evt);
            }
        });

        editarExameSangueBtn.setText("Editar Exame Sangue");
        editarExameSangueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarExameSangueBtnActionPerformed(evt);
            }
        });

        editarExameBioBtn.setText("Editar Exame Bioquimico");
        editarExameBioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarExameBioBtnActionPerformed(evt);
            }
        });

        exibirEstatisticaBtn.setText("Exibir Estatísticas");
        exibirEstatisticaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirEstatisticaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualizarExameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(procurarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastrarExameSangueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastrarExameBioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarExameSangueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarExameBioBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exibirEstatisticaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(Titulo)
                .addGap(29, 29, 29)
                .addComponent(visualizarExameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(procurarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarExameSangueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarExameBioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarExameSangueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarExameBioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exibirEstatisticaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarExameSangueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarExameSangueBtnActionPerformed
        app.mudaPainel(PAINEL_CADASTRAR_EXAME_SANGUE);
    }//GEN-LAST:event_cadastrarExameSangueBtnActionPerformed

    private void procurarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarBtnActionPerformed
        app.mudaPainel(PAINEL_PROCURAR_EXAME);
    }//GEN-LAST:event_procurarBtnActionPerformed

    private void visualizarExameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarExameBtnActionPerformed
        app.mudaPainel(PAINEL_VISUALIZAR_EXAMES);
    }//GEN-LAST:event_visualizarExameBtnActionPerformed

    private void cadastrarExameBioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarExameBioBtnActionPerformed
        app.mudaPainel(PAINEL_CADASTRAR_EXAME_BIOQUIMICO);
    }//GEN-LAST:event_cadastrarExameBioBtnActionPerformed

    private void editarExameSangueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarExameSangueBtnActionPerformed
        app.mudaPainel(PAINEL_EDITAR_EXAME_SANGUE);
    }//GEN-LAST:event_editarExameSangueBtnActionPerformed

    private void editarExameBioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarExameBioBtnActionPerformed
        app.mudaPainel(PAINEL_EDITAR_EXAME_BIOQUIMICO);
    }//GEN-LAST:event_editarExameBioBtnActionPerformed

    private void exibirEstatisticaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirEstatisticaBtnActionPerformed
        app.mudaPainel(PAINEL_EXIBIR_ESTATISTICAS);
    }//GEN-LAST:event_exibirEstatisticaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton cadastrarExameBioBtn;
    private javax.swing.JButton cadastrarExameSangueBtn;
    private javax.swing.JButton editarExameBioBtn;
    private javax.swing.JButton editarExameSangueBtn;
    private javax.swing.JButton exibirEstatisticaBtn;
    private javax.swing.JButton procurarBtn;
    private javax.swing.JButton visualizarExameBtn;
    // End of variables declaration//GEN-END:variables
}
