/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.trabalhoFinal.UI;

import com.trabalhoFinal.Dominio.Exame;
import com.trabalhoFinal.Lista.GerenciadorDeExame;
import javax.swing.DefaultListModel;

/**
 *
 * @author lucas
 */
public class ProcurarExamePainel extends javax.swing.JPanel {

    private GerenciadorDeExame gerenciadorDeExame;
    private App app;

    /**
     * Creates new form ProcurarExamePanel
     */
    public ProcurarExamePainel(GerenciadorDeExame gerenciadorDeExame, App app) {
        super();
        this.gerenciadorDeExame = gerenciadorDeExame;
        this.app = app;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        txtIdPaciente = new javax.swing.JTextField();
        procurarExameListaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPacienteEncontrado = new javax.swing.JList<>();
        voltarBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtTitulo.setText("Digite o id do paciente");

        txtIdPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIdPaciente.setMinimumSize(new java.awt.Dimension(70, 40));

        procurarExameListaBtn.setText("Procurar");
        procurarExameListaBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        procurarExameListaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarExameListaBtnActionPerformed(evt);
            }
        });

        listaPacienteEncontrado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPacienteEncontrado);

        voltarBtn.setText("Voltar");
        voltarBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txtTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(procurarExameListaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(txtTitulo)
                .addGap(18, 18, 18)
                .addComponent(txtIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(procurarExameListaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void procurarExameListaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarExameListaBtnActionPerformed
        String id = txtIdPaciente.getText().trim();

        if (id.isEmpty()) {
            exibirMensagemNaLista("Por favor, digite um ID.");
            return;
        }

        try {
            Exame exame = gerenciadorDeExame.procurarExame(id);
            if (exame != null) {
                exibirExameNaLista(exame);
            } else {
                exibirMensagemNaLista("Exame não encontrado.");
            }
        } catch (NumberFormatException e) {
            exibirMensagemNaLista("Por favor, insira um ID válido.");
        }
    }//GEN-LAST:event_procurarExameListaBtnActionPerformed

    private void exibirExameNaLista(Exame exame) {
        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement(exame.toString()); // Supondo que toString() de Exame retorna informações formatadas
        listaPacienteEncontrado.setModel(model);
    }

    private void exibirMensagemNaLista(String mensagem) {
        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement(mensagem);
        listaPacienteEncontrado.setModel(model);
    }
    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        app.mudaPainel(App.PAINEL_PRINCIPAL);
        limparCampos();
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void limparCampos() {
        txtIdPaciente.setText("");

        DefaultListModel<String> model = new DefaultListModel<>();
        listaPacienteEncontrado.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPacienteEncontrado;
    private javax.swing.JButton procurarExameListaBtn;
    private javax.swing.JTextField txtIdPaciente;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables

}
